In [45]:
import os
import tensorflow as tf
import numpy as np
import pandas as pd

# Load the training dataset from the local path
test_data_path = r"C:\Users\ASUS\Desktop\pro\pro\test.csv\test.csv"
test_data = pd.read_csv(test_data_path)

# Load the training dataset from the local path


train_data_path = r"C:\Users\ASUS\Desktop\pro\pro\train.csv\train.csv"
train_data = pd.read_csv(train_data_path)


physical_devices = tf.config.list_physical_devices('GPU')

data = pd.read_csv(r"C:\Users\ASUS\Desktop\pro\pro\train.csv\train.csv")

data.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [5]:
!git clone https://github.com/whitehatjr1001/comment-toxicity-detecttion-.git

'git' is not recognized as an internal or external command,
operable program or batch file.


id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [3]:
data.count(axis=1,numeric_only=True)

0         6
1         6
2         6
3         6
4         6
         ..
159566    6
159567    6
159568    6
159569    6
159570    6
Length: 159571, dtype: int64

In [4]:
x=data['toxic'].value_counts()[0]
x


144277

In [5]:
y=data['toxic'].value_counts()[1]
y


15294

In [6]:
x = data['comment_text']
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

### 

preprosseing


In [7]:
from tensorflow.keras.layers import TextVectorization 

In [8]:
X=data['comment_text']
Y=data[data.columns[2:]]



In [9]:
MAX_FETURES=200000

In [10]:
vecterizor = TextVectorization(max_tokens=MAX_FETURES,output_sequence_length=1800,output_mode='int')

In [11]:
type(X)


pandas.core.series.Series

In [12]:
type(X.values)

numpy.ndarray

In [13]:
vecterizor.adapt(X.values)

In [14]:
vectorized_text=vecterizor(X.values)

In [15]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [16]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, Y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [17]:
dataset.as_numpy_iterator().next()
(batch_x,batch_y)=dataset.as_numpy_iterator().next()

In [18]:
batch_x.shape

(16, 1800)

In [19]:
batch_y.shape

(16, 6)

competing the pieline by particining the data set into train test and vald


In [20]:
train=dataset.take(int(len(dataset)*7))
vald=dataset.skip(int(len(dataset)*7)).take(int(len(dataset)*2))
test=dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))


In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Dropout,Bidirectional,Embedding

In [22]:
'''model = Sequential()
# Create the embedding layer 
model.add(Embedding(MAX_FETURES+1, 32))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
#model.add(Dropout(0.2))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.01))
model.add(Dense(128, activation='relu'))
# Final layer 
model.add(Dense(6, activation='sigmoid'))'''


"model = Sequential()\n# Create the embedding layer \nmodel.add(Embedding(MAX_FETURES+1, 32))\n# Bidirectional LSTM Layer\nmodel.add(Bidirectional(LSTM(32, activation='tanh')))\n# Feature extractor Fully connected layers\nmodel.add(Dense(128, activation='relu'))\n#model.add(Dropout(0.2))\nmodel.add(Dense(256, activation='relu'))\nmodel.add(Dropout(0.01))\nmodel.add(Dense(128, activation='relu'))\n# Final layer \nmodel.add(Dense(6, activation='sigmoid'))"

In [23]:
#model.compile(loss='BinaryCrossentropy',optimizer='Adam')

In [24]:
#model.summary()

In [25]:
from keras.callbacks import EarlyStopping

In [26]:
es = EarlyStopping(monitor='val_loss',patience = 3, verbose=1,restore_best_weights=True)

In [27]:
model = tf.keras.models.load_model('commenttoxicity (1).h5')

In [28]:
history = model.fit(train, epochs=1,validation_data=vald,callbacks=[es])

9974/9974 [==============================] - ETA: 0s - loss: 0.0026

ValueError: Expected input data to be non-empty.

In [29]:
model.save('commenttoxicity.h5')

C:\Users\ASUS\Desktop\Subash\notebook\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [30]:
from matplotlib import pyplot as plt
plt.figure(figsize=(8,2))
pd.DataFrame(history.history).plot()
plt.show()

NameError: name 'history' is not defined

<Figure size 800x200 with 0 Axes>

predition time

In [31]:
batch=test.as_numpy_iterator().next() 

In [32]:
input_text=vecterizor('You are so horible. I hate you')

In [33]:
input_text

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([ 7, 20, 37, ...,  0,  0,  0], dtype=int64)>

In [34]:
np.expand_dims(input_text,0)

array([[ 7, 20, 37, ...,  0,  0,  0]], dtype=int64)

In [35]:
model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 1s 1s/step


array([[9.9764282e-01, 1.6429717e-02, 7.8357965e-02, 7.6308957e-08,
        8.9082551e-01, 6.8073568e-04]], dtype=float32)

In [36]:
model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 112ms/step


array([[9.9764282e-01, 1.6429717e-02, 7.8357965e-02, 7.6308957e-08,
        8.9082551e-01, 6.8073568e-04]], dtype=float32)

In [37]:
batch_X,batch_Y=test.as_numpy_iterator().next() 

In [38]:
(model.predict(batch_X)>0.5).astype(int)

1/1 [==============================] - 0s 185ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [39]:
batch_Y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [40]:
res=model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 121ms/step


In [41]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [42]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [43]:
for batch in test.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch
    # Make a prediction 
    yhat = model.predict(X_true)
    
    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

1/1 [==============================] - 0s 272ms/step


1/1 [==============================] - 0s 174ms/step


1/1 [==============================] - 0s 114ms/step


1/1 [==============================] - 0s 91ms/step


1/1 [==============================] - 0s 87ms/step


1/1 [==============================] - 0s 96ms/step


1/1 [==============================] - 0s 125ms/step


In [44]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.9886072278022766, Recall:0.993701696395874, Accuracy:0.6078234910964966
